catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# HLS run script generated by v++ compiler
# 

open_project stencil
set_top stencil
# v++ -g, -D, -I, --advanced.prop kernel.stencil.kernel_flags
add_files "/home/atefehSZ/hls/stencil/case1/hls-kernel/__merlinkernel_stencil.c" -cflags " -D XILINX -I /home/atefehSZ/hls/stencil/case1/hls-kernel"
open_solution -flow_target vitis solution
set_part xcu200-fsgd2104-2-e
# v++ --hls.clock or --kernel_frequency
create_clock -period 250MHz -name default
# v++ -g or --profile_kernel stall
config_rtl -kernel_profile
# v++ --advanced.param compiler.hlsDataflowStrictMode
config_dataflow -strict_mode warning
# v++ -g
config_debug -enable
# v++ --advanced.param compiler.deadlockDetection
config_export -disable_deadlock_detection=true
# v++ --advanced.param compiler.axiDeadLockFree
config_rtl -m_axi_conservative_mode=1
config_interface -m_axi_addr64
# v++ --hls.max_memory_ports
config_interface -m_axi_auto_max_ports=0
config_export -format ip_catalog -ipname stencil
# v++ --hls.pre_tcl or --advanced.prop solution.hls_pre_tcl
csynth_design
export_design
close_project
puts "HLS completed successfully"
exit
