#catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# Hls run script generated by the compiler
# 

#set xocc_optimize_level 0
open_project KERNEL_NAME
set_top KERNEL_NAME
add_files "KERNEL_SRC" -cflags " -D XILINX -I ./ KERNEL_FLAGS"
#add_files -tb
open_solution solution
set_part KERNEL_DEVICE
create_clock -period 300MHz -name default
#config_sdx -target xocc
#config_export -vivado_optimization_level $xocc_optimize_level
#config_dataflow -strict_mode warning
#set_clock_uncertainty 27.000000%
#config_interface -m_axi_addr64
config_export -format ip_catalog -ipname KERNEL_NAME
#csim_design
#csynth_design
#cosim_design
#export_design
close_project
exit
