catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# HLS run script generated by v++ compiler
# 

open_project bbgemm
set_top bbgemm
# v++ -g, -D, -I, --advanced.prop kernel.bbgemm.kernel_flags
add_files "./__merlinkernel_bbgemm.c" -cflags " -D XILINX -I ./ "
open_solution -flow_target vitis solution
set_part xcu200-fsgd2104-2-e
# v++ --hls.clock or --kernel_frequency
create_clock -period 250MHz -name default
# v++ -g or --profile_kernel stall
config_rtl -kernel_profile
# v++ --advanced.param compiler.hlsDataflowStrictMode
config_dataflow -strict_mode warning
# v++ -g
config_debug -enable
# v++ --advanced.param compiler.deadlockDetection
config_export -deadlock_detection none
# v++ --advanced.param compiler.axiDeadLockFree
config_interface -m_axi_conservative_mode=1
config_interface -m_axi_addr64
# v++ --hls.max_memory_ports
config_interface -m_axi_auto_max_ports=0
config_export -format xo -ipname bbgemm
# v++ --hls.pre_tcl or --advanced.prop solution.hls_pre_tcl
#source "/home/atefehSZ/RL/original-software-gnn/software-gnn/dse_database/save/merlin_prj/gemm-blocked/work_dir/merlin_33na0yin/.merlin_prj/run/implement/exec/hls/my_hls_pre.tcl"
csynth_design
export_design
close_project
puts "HLS completed successfully"
exit
