#catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# Hls run script generated by the compiler
# 

#set xocc_optimize_level 0
open_project bbgemm
set_top bbgemm
#add_files __merlinkernel_bbgemm.c -cflags " -D XILINX -I ./ -D XILINX -DAP_INT_MAX_W=4096"
add_files __merlinkernel_bbgemm.c -cflags " -D XILINX -I ./ "
#add_files -tb
open_solution -flow_target vitis solution
set_part xcu200-fsgd2104-2-e
create_clock -period 250MHz -name default
# config_rtl -kernel_profile

#config_sdx -target xocc
#config_export -vivado_optimization_level $xocc_optimize_level
# config_dataflow -strict_mode warning
# config_debug -enable
# config_export -disable_deadlock_detection=true
#set_clock_uncertainty 27.000000%
# config_rtl -m_axi_conservative_mode=1
# config_interface -m_axi_addr64
# config_interface -m_axi_auto_max_ports=0
config_export -format ip_catalog -ipname bbgemm
#csim_design
csynth_design
#cosim_design
export_design 
close_project
exit
